import type { Exercise } from '../../src/prisma-client';
import { MuscleGroupLabel, RecordSetsType } from '../../src/prisma-client';

type ExerciseSeed = Pick<
  Exercise,
  'label' | 'recordSetsType' | 'isIsometric' | 'isUnilateral' | 'bwFactor'
> & {
  primaryMuscleGroupLabels: MuscleGroupLabel[];
  secondaryMuscleGroupLabels: MuscleGroupLabel[];
  tertiaryMuscleGroupLabels: MuscleGroupLabel[];
};

export const exercises: ExerciseSeed[] = [
  {
    label: 'Pull up (assisted)',
    recordSetsType: RecordSetsType.BODYWEIGHT_MINUS_OFFSET,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: null, // net bodyweight via BODYWEIGHT_MINUS_OFFSET record type
    primaryMuscleGroupLabels: [MuscleGroupLabel.LATISSIMUS_DORSI],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.BICEPS, MuscleGroupLabel.RHOMBOIDS],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.FOREARMS, MuscleGroupLabel.ABDOMINALS],
  },
  {
    label: 'Chest press machine',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: null,
    primaryMuscleGroupLabels: [
      MuscleGroupLabel.PECTORALIS_MAJOR,
      MuscleGroupLabel.FRONT_DELTOIDS,
      MuscleGroupLabel.TRICEPS,
    ],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.PECTORALIS_MINOR],
    tertiaryMuscleGroupLabels: [],
  },
  {
    label: 'Dead hang',
    recordSetsType: RecordSetsType.TIME,
    isIsometric: true,
    isUnilateral: false,
    bwFactor: 1.0,
    primaryMuscleGroupLabels: [MuscleGroupLabel.FOREARMS],
    secondaryMuscleGroupLabels: [
      MuscleGroupLabel.LATISSIMUS_DORSI,
      MuscleGroupLabel.TRAPEZIUS,
      MuscleGroupLabel.REAR_DELTOIDS,
    ],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.ABDOMINALS, MuscleGroupLabel.BICEPS],
  },
  {
    label: "Farmer's carry",
    recordSetsType: RecordSetsType.WEIGHT_AND_TIME,
    isIsometric: true,
    isUnilateral: false,
    bwFactor: null,
    primaryMuscleGroupLabels: [MuscleGroupLabel.FOREARMS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.TRAPEZIUS, MuscleGroupLabel.ABDOMINALS],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.GLUTES, MuscleGroupLabel.CALVES],
  },
  {
    label: 'Butterfly machine',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: null,
    primaryMuscleGroupLabels: [
      MuscleGroupLabel.PECTORALIS_MAJOR,
      MuscleGroupLabel.PECTORALIS_MINOR,
    ],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.FRONT_DELTOIDS],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.BICEPS],
  },
  {
    label: 'Lat pulldown',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: null,
    primaryMuscleGroupLabels: [MuscleGroupLabel.LATISSIMUS_DORSI],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.BICEPS, MuscleGroupLabel.RHOMBOIDS],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.REAR_DELTOIDS],
  },
  {
    label: 'Leg press horizontal',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: null,
    primaryMuscleGroupLabels: [MuscleGroupLabel.QUADRICEPS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.GLUTES],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.HAMSTRINGS],
  },
  {
    label: 'Seated row',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: null,
    primaryMuscleGroupLabels: [MuscleGroupLabel.RHOMBOIDS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.BICEPS, MuscleGroupLabel.LATISSIMUS_DORSI],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.REAR_DELTOIDS],
  },
  {
    label: 'Shoulder press (dumbell)',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: null,
    primaryMuscleGroupLabels: [MuscleGroupLabel.FRONT_DELTOIDS, MuscleGroupLabel.MEDIAL_DELTOIDS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.TRICEPS],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.PECTORALIS_MINOR],
  },
  {
    label: 'Single leg sit-to-stand',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: true,
    bwFactor: 0.6,
    primaryMuscleGroupLabels: [MuscleGroupLabel.QUADRICEPS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.GLUTES],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.ABDOMINALS, MuscleGroupLabel.CALVES],
  },
  {
    label: 'Bulgarian split squat',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: true,
    bwFactor: 0.5,
    primaryMuscleGroupLabels: [MuscleGroupLabel.QUADRICEPS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.GLUTES],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.ADDUCTORS, MuscleGroupLabel.ABDOMINALS],
  },
  {
    label: 'Reverse lunge',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: true,
    bwFactor: 0.5,
    primaryMuscleGroupLabels: [MuscleGroupLabel.QUADRICEPS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.GLUTES],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.HAMSTRINGS, MuscleGroupLabel.ABDOMINALS],
  },
  {
    label: 'Plank',
    recordSetsType: RecordSetsType.TIME,
    isIsometric: true,
    isUnilateral: false,
    bwFactor: 0.5,
    primaryMuscleGroupLabels: [MuscleGroupLabel.ABDOMINALS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.OBLIQUES],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.REAR_DELTOIDS, MuscleGroupLabel.QUADRICEPS],
  },
  {
    label: 'Side plank',
    recordSetsType: RecordSetsType.TIME,
    isIsometric: true,
    isUnilateral: true,
    bwFactor: 0.5,
    primaryMuscleGroupLabels: [MuscleGroupLabel.OBLIQUES],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.ABDOMINALS],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.REAR_DELTOIDS, MuscleGroupLabel.GLUTES],
  },
  {
    label: 'Reverse crunch',
    recordSetsType: RecordSetsType.REPS,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: 0.2,
    primaryMuscleGroupLabels: [MuscleGroupLabel.ABDOMINALS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.OBLIQUES],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.HIP_FLEXORS],
  },
  {
    label: 'Superman',
    recordSetsType: RecordSetsType.REPS,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: 0.2,
    primaryMuscleGroupLabels: [MuscleGroupLabel.ERECTOR_SPINAE],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.GLUTES],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.HAMSTRINGS],
  },
  {
    label: 'Bench press (barbell)',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: null,
    primaryMuscleGroupLabels: [MuscleGroupLabel.PECTORALIS_MAJOR],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.TRICEPS],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.FRONT_DELTOIDS],
  },
  {
    label: 'Pull up',
    recordSetsType: RecordSetsType.BODYWEIGHT_PLUS_WEIGHT,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: 1.0,
    primaryMuscleGroupLabels: [MuscleGroupLabel.LATISSIMUS_DORSI],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.BICEPS, MuscleGroupLabel.RHOMBOIDS],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.FOREARMS, MuscleGroupLabel.ABDOMINALS],
  },
  {
    label: 'Leg extension',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: null,
    primaryMuscleGroupLabels: [MuscleGroupLabel.QUADRICEPS],
    secondaryMuscleGroupLabels: [],
    tertiaryMuscleGroupLabels: [],
  },
  {
    label: 'Tricep dips',
    recordSetsType: RecordSetsType.BODYWEIGHT_PLUS_WEIGHT,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: 1.0,
    primaryMuscleGroupLabels: [MuscleGroupLabel.TRICEPS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.PECTORALIS_MAJOR],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.FRONT_DELTOIDS],
  },
  {
    label: 'Back extension',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: 0.5,
    primaryMuscleGroupLabels: [MuscleGroupLabel.ERECTOR_SPINAE],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.GLUTES],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.HAMSTRINGS],
  },
  {
    label: 'Hip thrusts',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: 0.5,
    primaryMuscleGroupLabels: [MuscleGroupLabel.GLUTES],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.HAMSTRINGS],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.ABDOMINALS],
  },
  {
    label: 'Step ups',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: true,
    bwFactor: 1.0,
    primaryMuscleGroupLabels: [MuscleGroupLabel.QUADRICEPS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.GLUTES],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.CALVES, MuscleGroupLabel.ABDOMINALS],
  },
  {
    label: 'Cable kickbacks',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: true,
    bwFactor: null,
    primaryMuscleGroupLabels: [MuscleGroupLabel.GLUTES],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.HAMSTRINGS],
    tertiaryMuscleGroupLabels: [],
  },
  {
    label: 'Romanian deadlift',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: null,
    primaryMuscleGroupLabels: [MuscleGroupLabel.HAMSTRINGS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.GLUTES],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.ERECTOR_SPINAE, MuscleGroupLabel.FOREARMS],
  },
  {
    label: 'Concentration curls',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: true,
    bwFactor: null,
    primaryMuscleGroupLabels: [MuscleGroupLabel.BICEPS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.FOREARMS],
    tertiaryMuscleGroupLabels: [],
  },
  {
    label: 'Bench press (dumbell)',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: null,
    primaryMuscleGroupLabels: [MuscleGroupLabel.PECTORALIS_MAJOR],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.TRICEPS],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.FRONT_DELTOIDS],
  },
  {
    label: 'Crunch',
    recordSetsType: RecordSetsType.REPS,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: 0.2,
    primaryMuscleGroupLabels: [MuscleGroupLabel.ABDOMINALS],
    secondaryMuscleGroupLabels: [],
    tertiaryMuscleGroupLabels: [],
  },
  {
    label: 'Deadlift',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: null,
    primaryMuscleGroupLabels: [MuscleGroupLabel.GLUTES, MuscleGroupLabel.HAMSTRINGS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.FOREARMS, MuscleGroupLabel.TRAPEZIUS],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.ERECTOR_SPINAE, MuscleGroupLabel.ABDOMINALS],
  },
  {
    label: 'Dumbbell squats',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: null,
    primaryMuscleGroupLabels: [MuscleGroupLabel.QUADRICEPS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.GLUTES],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.ERECTOR_SPINAE, MuscleGroupLabel.ABDOMINALS],
  },
  {
    label: 'Lunge',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: true,
    bwFactor: 0.5,
    primaryMuscleGroupLabels: [MuscleGroupLabel.QUADRICEPS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.GLUTES],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.HAMSTRINGS],
  },
  {
    label: 'Cable Twist (Down to up)',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: true,
    bwFactor: null,
    primaryMuscleGroupLabels: [MuscleGroupLabel.OBLIQUES],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.ABDOMINALS],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.REAR_DELTOIDS],
  },
  {
    label: 'Cable Twist (Up to down)',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: true,
    bwFactor: null,
    primaryMuscleGroupLabels: [MuscleGroupLabel.OBLIQUES],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.ABDOMINALS],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.REAR_DELTOIDS],
  },
  {
    label: 'Dead Bug',
    recordSetsType: RecordSetsType.REPS,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: 0.1,
    primaryMuscleGroupLabels: [MuscleGroupLabel.ABDOMINALS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.OBLIQUES],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.HIP_FLEXORS],
  },
  {
    label: 'Flutter Kicks',
    recordSetsType: RecordSetsType.REPS,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: 0.1,
    primaryMuscleGroupLabels: [MuscleGroupLabel.ABDOMINALS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.HIP_FLEXORS],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.QUADRICEPS],
  },
  {
    label: 'Renegade Row (dumbbell)',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: true,
    bwFactor: null,
    primaryMuscleGroupLabels: [MuscleGroupLabel.RHOMBOIDS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.ABDOMINALS, MuscleGroupLabel.BICEPS],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.FRONT_DELTOIDS],
  },
  {
    label: 'Russian Twist',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: 0.3,
    primaryMuscleGroupLabels: [MuscleGroupLabel.OBLIQUES],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.ABDOMINALS],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.HIP_FLEXORS],
  },
  {
    label: 'Box jump',
    recordSetsType: RecordSetsType.REPS,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: 1.0,
    primaryMuscleGroupLabels: [
      MuscleGroupLabel.QUADRICEPS,
      MuscleGroupLabel.GLUTES,
      MuscleGroupLabel.HAMSTRINGS,
      MuscleGroupLabel.CALVES,
    ],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.HIP_FLEXORS],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.ABDOMINALS, MuscleGroupLabel.OBLIQUES],
  },
  {
    label: 'Single leg box jump',
    recordSetsType: RecordSetsType.REPS,
    isIsometric: false,
    isUnilateral: true,
    bwFactor: 1.0,
    primaryMuscleGroupLabels: [
      MuscleGroupLabel.QUADRICEPS,
      MuscleGroupLabel.GLUTES,
      MuscleGroupLabel.HAMSTRINGS,
      MuscleGroupLabel.CALVES,
    ],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.HIP_FLEXORS],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.ABDOMINALS, MuscleGroupLabel.OBLIQUES],
  },
  {
    label: 'Seated squat',
    recordSetsType: RecordSetsType.WEIGHT,
    isIsometric: false,
    isUnilateral: false,
    bwFactor: null,
    primaryMuscleGroupLabels: [MuscleGroupLabel.QUADRICEPS],
    secondaryMuscleGroupLabels: [MuscleGroupLabel.GLUTES],
    tertiaryMuscleGroupLabels: [MuscleGroupLabel.HAMSTRINGS],
  },
];
